### ISSUE TITLE
Cannot go get on Mac

### ISSUE THREAD

**Issue by rubenv** [mattn/go-ole#47]
I'm getting the following:
```
$ go get -v github.com/StackExchange/wmi
github.com/StackExchange/wmi (download)
github.com/mattn/go-ole (download)
github.com/mattn/go-ole
# github.com/mattn/go-ole
../../Go/src/github.com/mattn/go-ole/com.go:80: undefined: syscall.StringToUTF16Ptr
../../Go/src/github.com/mattn/go-ole/com.go:91: undefined: syscall.StringToUTF16Ptr
../../Go/src/github.com/mattn/go-ole/com.go:112: undefined: syscall.StringToUTF16Ptr
../../Go/src/github.com/mattn/go-ole/com.go:178: undefined: syscall.StringToUTF16Ptr
../../Go/src/github.com/mattn/go-ole/variables.go:8: undefined: syscall.NewLazyDLL
../../Go/src/github.com/mattn/go-ole/variables.go:9: undefined: syscall.LoadDLL
../../Go/src/github.com/mattn/go-ole/variables.go:10: undefined: syscall.LoadDLL
../../Go/src/github.com/mattn/go-ole/variables.go:11: undefined: syscall.LoadDLL
../../Go/src/github.com/mattn/go-ole/variables.go:12: undefined: syscall.LoadDLL
../../Go/src/github.com/mattn/go-ole/variables.go:13: undefined: syscall.LoadDLL
../../Go/src/github.com/mattn/go-ole/com.go:178: too many errors
```

You might be wondering: why on earth would you want a Windows module on OSX? Because we're building a cross-platform app that we cross-compile.

Do you have any recommendations on how we can solve / work around this?

**Comment by stefanschneider** [comment]
You could add " // +build windows " on your go files that have dependency on go-ole and skip the `go get -v github.com/StackExchange/wmi`. This requires all calls related to go-ole to be in a dedicated windows file.

Even if there would be a " // +build windows " in the go-ole library your package would still fail to compile.

npipe ( https://github.com/natefinch/npipe ) is another example of a windows specific wrapper lib that doesn't work (i.e. go get) on platforms  different from windows.

I am not aware of a simple way to have a platform specific package be successful on `go get`, but fail at runtime.

**Comment by mjibson** [comment]
The winsvc package, perhaps the best example of a Go Windows package, uses build comments as @stefanschneider suggested: https://code.google.com/p/winsvc/source/browse/svc/event.go#5

I believe go-ole should add them to all its files.

**Comment by rubenv** [comment]
@mjibson is probably right.

As it stands we can't use go-ole in our project, even when we isolate it in `+build windows` files: our CI server will `go get` all dependencies before a build (and `go get` does a compile by default).

Putting flags on the windows-only files would solve this.

Would you accept a patch for this?

**Comment by jacobsantos** [comment]
Is this fixed and can be closed?

**Comment by mjibson** [comment]
Not quite. Here's the output from linux or mac:

```
% go get github.com/mattn/go-ole
# github.com/mattn/go-ole
/go/src/github.com/mattn/go-ole/vt_string.go:31: undefined: VT
```
