### ISSUE TITLE
How to get returned data from the MustCallMethod?

### ISSUE THREAD

**Issue by MelleBoudewijnsSMTS** [mattn/go-ole#57]
Hi, 
The source below is returning a version information as a string. But how to get it from dbinfo?

dbinfo := oleutil.MustCallMethod(conversationSystem, "Request", "Version").ToIDispatch()

**Comment by mattn** [comment]
Please let me known the description. Which COM are you using, What do you expect?

**Comment by MelleBoudewijnsSMTS** [comment]
I'm using a special program where the Request of Version will return the version number as string. Or for examble, a request of DatabaseName will return the database as string. Can I find the returned string somwehre in the dbinfo object (in the example above). The system also support properties; they work fine and I get them in Go. It's just the returned string of the MustCallMethod.

**Comment by mattn** [comment]
What structure of methods? For example in VBS, version is BYREF argument like below?

```vbs
Dim version
Call conversationSystem.Request(version)
```

**Comment by jacobsantos** [comment]
Closing unless further comment requested.
