### ISSUE TITLE
Structuring of codebase

### ISSUE THREAD

**Issue by jacobsantos** [mattn/go-ole#58]
I was thinking about restructuring and I was wanting some feedback before I start working on this with my fork. The question is whether this would be accepted if I went ahead with this idea. As well as what would be broken and have to be changed for those already using this library.

TL;DR: Move the code from the current base directory to child directories so someone can `go get github.com/mattn/go-ole/core` and `go get github.com/mattn/go-ole/core-shared` and `go get github.com/mattn/go-ole/oleutil` instead of having to download everything.

 * ./core
 * ./core-shared
 * ./core-cgo
 * ./oleutil
 * ./examples
 * ./documentation
 * ./test
 * ./test/project
 * ./test/data

`Core` directory would contain all of the class structures that be type casted for COM. It would also include interfaces for `core-shared` and `core-cgo` to implement, so that you could use either one. Most of the code that could be used throughout the other packages would be contained in `core`.

`Core-shared` directory would contain most of the existing code with modifications to match interfaces in `core`.

`Core-Cgo` directory will mostly not exist until it is started by someone. It will be the cgo dependency for COM.

`Oleutil` directory will contain the current `oleutil`. I was also thinking of moving some of the helper code I created to here as well or simply removing the helper code I created, since it probably isn't being used.

`Test/Project` directory will include the Visual Studio Community 2013 project for the C# COM server for testing.

`Documentation` directory will contain the documentation files for describing how to use the library for Google Go. This should include the motivations behind the library structure and oleutil usage.

**Comment by mattn** [comment]
I prefer lower case name of directory or files. And package name should be snake_case so `core-shared` should be `core_shared`, `core-cgo` should be `core_cgo`. Or just `common`, `shared`, etc.

**Comment by jacobsantos** [comment]
Okay. I will go with `common`.

**Comment by jacobsantos** [comment]
I forgot I already tried to do this and how much of a bad idea it was previously. Shows how long ago that was. I think with the restructuring that I'm going to go ahead and add any missing interfaces and add support for all of the COM functions, constants and library. Or as much as possible through shared library calls.

I am calling this version 0.2.0, since the unofficial current version is 0.1.0. I thought about calling it version 1.0.0, but the current go-ole library is incomplete and 1.0.0 should be complete. I'm hoping that people won't mistake it for unstable with the low version number.

With the restructuring I'm moving names to be more Go idiomatic. The current COM names from the C API will still be available to ensure that developers from other languages will have an easier time moving over to Go OLE library. It will be up to the developer whether they want to go with Go idiomatic names or COM names.

Backwards compatibility will be attempted for 0.1.0. The Go Generate tool for generating Go code off of COM could support 0.1.0, but will require version 0.2.0 of the library.

--------------

I'm also looking at cgo. I need to do some research with how Go 1.5.0 is going to affect binding to C. I don't really think it will affect anything.

The reason I'm thinking of going ahead and implementing it for now is how interfacing between the shared library and cgo will work. By that I mean it will work based on interfaces and function type aliases. I'm thinking the final product will be more roundabout to allow for either shared or cgo, but implementing both at the same time will provide an incentive and better testing for whether the implementation will actually work.

-------------

I am also thinking it might be better to work on the test tool to be released with version 0.2.0 as well. Given how many changes and how much support is going to be required. Something to think about, but probably going to just wait until 0.3.0 for this and focus on just making sure the existing tests still work.

-------------

Documentation was started on my fork and I'm going to continue as I work on the restructuring of the code. I'm going to shoot for being able to put the documentation on one of the existing sites. I hope to at least have every type documented with at least a summary. Eventually going for examples and longer descriptions. 

I suck royally at technical writing, but I guess that if it is at least provided that someone will jump on that and reduce the suck.

--------------

As always, work continues on my fork. It is looking like it will be a few weeks or months before it will be ready. Looks like more than just this ticket will be completed when I'm done. If not documentation ticket, then at least the tool ticket. My motivation is to complete the `go generate` tool, so I'm not going to tag 0.2.0 until the tool is completed.

Once I'm finished, I'll do a merge request into develop and hopefully people will look at it and review and test before merging into master.

**Comment by jacobsantos** [comment]
Oh, I'm also including a ChangeLog and will convert some of the notes to an Upgrade Guide for when 0.2.0 is released. Might be something to maintain for 0.3.0 and beyond.

**Comment by mgspross** [comment]
@jacobsantos @mattn I second the suggestion for single-word package names (`common`, `shared`, etc.). Quoting Effective Go's [section on package names](https://golang.org/doc/effective_go.html#package-names) (emphasis mine):

> It's helpful if everyone using the package can use the same name to refer to its contents, which implies that the package name should be good: short, concise, evocative. **By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps**

I tend to agree with this: package names that are single words are more idiomatic.

**Comment by mattn** [comment]
+1 to single word package name.

**Comment by jacobsantos** [comment]
My fork may have gotten crazy with package amount and names. I'm thinking I'm going to fix that somewhat once more of the library is completed. I'm liking the structure changes and improvements.

Here are the packages:

 * api
 * cgo
 * com
 * connect (will be removed)
 * iconnectionpoint
 * iconnectionpointcontainer
 * idispatch
 * iinspectable
 * iprovideclassinfo
 * itypecomp
 * itypeinfo
 * itypelib
 * iunknown
 * shared
 * variant

I'm thinking of moving `api` and `variant` back to `com`.

The way the library works is `api` has functions that the rest of the library calls. `cgo` and `shared` packages register their functions with `api`.

```golang
import _ "github.com/mattn/go-ole/pkg/shared"
```

or

```golang
import _ "github.com/mattn/go-ole/pkg/cgo"
```

The `com` package and `api` package can be built on any platform. It should be possible to have the interface packages (`idispatch`, `iunknown`, etc) able to be built on any platform, but at the moment this isn't available.

I think the structure changes are pretty much finalized, but I could use some feedback. I'm not sure about the interface packages or whether they are should be under another directory.

Like:

 * go-ole/api
 * go-ole/cgo
 * go-ole/com
 * go-ole/shared
 * go-ole/variant
 * go-ole/pkg/iconnectionpoint
 * go-ole/pkg/iconnectionpointcontainer
 * go-ole/pkg/idispatch
 * go-ole/pkg/iinspectable
 * go-ole/pkg/iprovideclassinfo
 * go-ole/pkg/itypecomp
 * go-ole/pkg/itypeinfo
 * go-ole/pkg/itypelib
 * go-ole/pkg/iunknown

The reason for putting everything under `pkg` is to not confused with other directories in the root repository.

**Comment by mattn** [comment]
well, I don't like `pkg` because i'm thinking `idispatch`, `iunknown` is basically libraries for manipurating COM. sorry, I may not understand yet what you are doing.

**Comment by mgspross** [comment]
I'm not sure about `pkg` either. What I am worried about is having to import each of the interfaces separately when you are using `go-ole`. I feel like you should only need to import one package ideally when you are actually using the library.

With the proposed packaging, if I have a COM class that implements `IDispatch` and which raises events, all of the following imports would be needed to support it:

* go-ole/com
* go-ole/variant
* go-ole/pkg/iconnectionpoint
* go-ole/pkg/iconnectionpointcontainer
* go-ole/pkg/idispatch
* go-ole/pkg/iunknown

And possibly a few more, since I'm not sure if `api` or `shared` would be needed or not.

In my mind, most of those packages would tend to be used together, so they should probably be in one package, not split up.

I see it as a tradeoff between organizing the projects in multiple subpackages to make development easier versus keeping the package layout simple for end-users of the library.

Instead of creating separate packages for the COM interfaces (`IUnknown, `IDispatch`, etc.), for example, they could be all be put into a single `interfaces` package (or `ifaces` if you like short names), or just kept under the top-level `com` package, with no subpackage at all.

I tend to look at it like this: if I am using `go-ole`, I tend to think I should only need to import one or two packages to get the most common/important functionality, and there may still be other subpackages for functionality and features that are used less often or for things which are purely internal to the library and not part of the documented API.

**Comment by jacobsantos** [comment]
To be honest, I'm not sure `pkg` is a good name either. The only thing I do know is that I do like that each COM interface has its own directory, because it is much more flexible and contained.

Right now, everything is under `pkg`, but I thought about changing that to `src` or just moving everything back to the repo root. I could also move all of the interface packages under `com` again.

The packages `idispatch` and `iunknown` have files and elements that are reused throughout other libraries. The idea is that https://github.com/jacobsantos/go-com/blob/master/pkg/iunknown/client.go can be reused in https://github.com/jacobsantos/go-com/blob/master/pkg/idispatch/interface.go.

@mattn My attempt is to formalize code generation for COM interfaces. Whatever I have now for the packages is how the code generation will work. I want to make sure that the current COM interface packages look and feel right before proceeding with the code generation tool.

It is possible to have everything in the same file and in the root package. I just don't think that is the cleanest solution. I do think that `api` and `variant` need to be moved back into the `com` package and the separation was really to see how it feels with development.

The problem with the code generation is that not everything will be able to be automatically generated, so the separate files exist for the developers to look at and confirm and change. The initial version of the code generation tool will attempt to generate as much as possible, but I noticed there are complexities to even the few supported interfaces that this might not be possible in the initial version.

@mgspross During the development of the current COM interface packages, I haven't really needed to import that many packages. I'm not sure how this will scale out with other packages. I will test this once the code generation tool is completed and I can start auto generating COM interface packages.

The `shared` or `cgo` packages only need to be imported where you `api.CoInitialize()`. The packages have `init()`, so technically, you might just be able to include it in the file of your `main()`. The idea is that you don't include it in your library, unless you have `main()`.

It does appear like `api` and `variant` will be moved back to `com`. It was good during development to move those out for further documentation, but it seems like everyone agrees that it should be part of `com`.

Really, I think the idea is that you don't have to manually specify the packages you are importing. The code generation tool builds you a COM interface package and you simply include that where you use it.

I think the purpose of this is to find out what the better way of developing the library should be. I didn't really account for the advantage of a small library. I am hoping that the code generation tool will reduce the amount of time and code the developer will need to use with the library.

My main goal is that you just code generate the COM code and just don't really need to use the COM library directly. Or as much as realistically possible.

**Comment by jacobsantos** [comment]
One other idea is that the `client.go` and `server.go` functions are moved to `com` and the COM interface packages use those instead. Really, the functions are what are important. The structures are just dressing.

**Comment by mgspross** [comment]
@jacobsantos I agree that if this is mainly to support the idea that you use a code generator and not `go-ole` directly, then the package structure for `go-ole` itself is less an issue.

I guess I'd be more concerned if using `go-ole` directly was still something we wanted to "officially" support, if for some reason someone can't use the code generator or the code generator isn't fully stable yet.

If the idea is that we are definitely moving in the direction of code generation (which I think would greatly simplify using COM from Go and am completely on board with), then I also agree that the package structure should be designed to simplify the implementation of the code generator, rather than needing to be easy-to-use for developers.

So, I guess the question if supporting a simpler package structure for developers using `go-ole` directly is worth considering, or if we are basically saying the right way to use `go-ole` will be to use the code generator.

I'd be fine with whatever we decide on that front, I just think we need a consensus on what this means for how we intend the library to be used (is it a library for the code generator to use, or a library for developers to use, or both).

**Comment by mgspross** [comment]
Something else to consider in all of this is how all of these changes will affect existing users of the library, because `go-ole` as it exists now won't be compatible with the version of `go-ole` we are discussing now.

So another question is should the "new" version actually have a different name altogether, to avoid confusion with the current `go-ole` library?

**Comment by jacobsantos** [comment]
@mgspross I was thinking about the simple version and I think it should be possible to generate a package that includes everything in a single package. It would not technically be compatible with the full library since it would require name changes to fit everything in the same package.

I'm not sure about the naming or version or both. A question for @mattn. I can still make changes to the structure and fork since everything is still unstable at the moment. Once I start the go generate tool, I'll be less inclined to change the library, unless building the tool is more difficult.

I'm not sure, it is obvious at this point that the code generation won't be able to generate all of the code required. Or at least at this point. I'm hoping that contributions will be made to support more and more code generation, so that in the future it will technically be possible to generate all of the code to where you don't need to write any library code.

I mean, why would you write code when you can just generate most of it? I'm not sure, I am hoping that the go:generate is the future of Go coding. However, support for using the library directly will also need to be supported. I'm not sure if this means that the library needs to have a build system that outputs a smaller package with just shared or cgo. Or if it just means developers will have to just reference the new packages.

Yes. This new fork will not be compatible with the current version. With the name changes and structure changes.

I think time will tell. I think that someone whom already has all of the code working may not want to rewrite or generate new code and then rewrite their current code.

I also think that once the testing tool is completed that more of COM library will be supported, so someone holding off using the library, may finally jump on board, because SafeArray types will be fully supported.

As for the numbers, I don't know. If the fork is merged back in and no one uses it for one reason or another, then changes will have to be made. I had wanted to make it backwards compatible, but that became a bit more difficult as development continued.

The `cgo` is experimental and I want to see how well it works. If it isn't used or serves no purpose, then it can be removed and the `shared` package merged back in.

I am hoping that people use this fork, mostly because I would like to see contributions to the code generation. It is an experiment for me, but I'm not tied to the changes. If no one uses it or likes it, then it will be moved back to parity with the current go-ole master.

**Comment by jacobsantos** [comment]
To reiterate, my focus is
 1. More support for COM / OLE / Automation functions in both the shared and cgo libraries.
 1. Renaming constants, functions, etc to more Go language style.
 1. COM go:generate tool.
 1. Test COM Server and move all tests and adding tests that uses the test COM server.
 1. Basic Guide documentation (gh-pages) and complete inline documentation (godoc.org).

I see a lot more developers contributing and I am hoping that the new code provides further foundation to build. I'm also curious as to whether the changes will increase contributions and usage.

I doubt that all of the changes, even if majority of the existing code is the same will work even with the COM server provided for testing. I do see that contributions are more, I have this itch and I want to deal with it, which nothing against that. I'm just hoping that the changes allow for more itches and more motivation for providing solutions.

After, I'll probably be done for another 2 years. It would be nice to finally get around to completing that one project that got me involved with this in the first place.

**Comment by jacobsantos** [comment]
Oh. The fork may also require Go 1.4.

**Comment by jacobsantos** [comment]
I am going to close this, the packages are back in root and I think the last issue with com interface packages can be worked out after a merge, if any.

I am currently working on extending the com library support. As well as other enhancements.

Thanks for the feedback!

**Comment by jacobsantos** [comment]
Actually, I found the structure can actually be put into one package. So instead of having `cgo` and `shared` in separate packages, they will all be in the `com` or `ole` package. I like `com` better since MSDN lists reference material under COM naming.

I'm going to have it to where if you compile for systems other than Windows, you get NOOP receiver methods and functions. This will be documented, but given programmers would most likely not read this information, it is also possible to panic instead.

I'm still haven't decided to move the packages back into the main package. I still think it is better to include those packages separately depending on your interface needs. I don't think the compiler links functions, types and structures that aren't used, but it might include them anyway in the off chance that the structure definition might be required at runtime.

It occurs to me that `IUnknown` and possibly `IDispatch` are two packages that should always exist, so what mgspross was getting at. Everything inherits from `IUnknown`. `IDispatch` is the main interface used with the library helpers. So moving them to the main package would reduce the amount of packages that you would need to include.

It will take a few days moving the code around to allow for it to be compiled in the same package.

**Comment by mattn** [comment]
I can rename this repository to "go-com".

**Comment by jacobsantos** [comment]
That might not be necessary. The package they use will be `com` and technically OLE is correct. I just like COM, because the OLE is based on the COM layer and the MSDN documentation is under COM. The problem is that searching on Google is difficult, because "com" is such a common name and OLE is not. The other reason is that COM includes OLE automation, SafeArray and COM+, among other things.

There is a lot more reflection, which is kind of neat, because it will function more like binary.Read() when using structures and slices. There is still an incredible amount to do, but I'm liking this new iteration. There is a lot of cleaning up of the existing code and the new utility functions should help with the code generation.
