### ISSUE TITLE
[Question] Go COM Server

### ISSUE THREAD

**Issue by jacobsantos** [mattn/go-ole#60]
Doing some research, it seems like it could be possible to have a COM Server in Go. Obviously, it couldn't be in-process or a DLL, but it could possibly be an executable. I'm also adding more functions that work with supporting COM servers.

Is there something that would inheritly prevent Go from being an remote or local executable COM Server process? If it is possible, then what is necessary to implement it or help developers with the library implement it?

If it is possible, then it could allow for removing the need for a C# testing application. The testing COM server application would just be Go.

**Comment by mattn** [comment]
Currently, go on windows doesn't support symbol export. And also generate dlls. I know `//export` in go code should work as export the symbol, but i'm not sure.

**Comment by jacobsantos** [comment]
It might require cgo. I'm trying to remember some detail that I thought prevented a COM server, even as an executable. That might actually be the problem, not being able to export. It would require manually creating or creating a tool to generate the TLB.

I don't suspect it is a big deal to not be able to create a COM server in Go. I'm just thinking that if it is possible, that it should at least be supported.

I'm still going to add the functions, in the case that it becomes possible in the future. I'm still doing research and I'm hoping the book comes up with something. I was thinking it could just write another .NET application to proxy, but no, that would be dumb. "Yo dog, I heard you like COM, so I put your COM inside of your COM."

I know the COM events are not possible, given that it requires a DLL, because events do not RPC.

**Comment by mattn** [comment]
COM server must export symbol `DLLSelfRegister`. If it is possible, probably, go can do it.

**Comment by mgspross** [comment]
>@jacobsantos: I know the COM events are not possible, given that it requires a DLL, because events do not RPC.

Actually, events can work with out-of-process (EXE) COM servers. Ultimately, events are just methods on COM interfaces, so COM/OLE can handle marshaling interfaces and parameters between processes the same way it can automatically marshal other COM calls.

In general, COM/OLE can marshal interfaces that implement `IDispatch` automatically, and event sink interfaces can implement `IDispatch`.

I've written COM server EXE's in the past (in VB6) that could raise events, but I've never tried doing this at a lower-level, so I'm not sure how much extra work - if any - is needed to do it from scratch. It's possible it will "just work" once the supporting functions are implemented in `go-ole`.

I just wanted to point out that this should be possible to support, at least in theory.

**Comment by jacobsantos** [comment]
@mgspross Cool. Thanks.

I am thinking I'm not going to implement this, other than providing the functions. Research seems to be fairly sparse for languages other than .NET and in-process COM server.

It would be nice to provide a Go out-of-process COM server instead of a .NET out-of-process COM server. I'm still going to develop the .NET COM server, since it seems like it will be quicker and easier.

It does seem like it is possible to provide a complete out-of-process COM server in Go. I think other than providing a more complete library supporting more COM functions and structures, it will be up to the developer to research and implement it themselves.

**Comment by jacobsantos** [comment]
This seems possible and functions will be added to support it.

**Comment by savely-krasovsky** [comment]
Writing in-process server was relatively easy, I successfully called some methods from C# demo caller. ~~But I am not sure about out-of-process. Probably RPC stuff should be written from scratch.~~. Actually it was pretty straightforward too, all you need is `CoRegisterClassObject`.

**Comment by jacobsantos** [comment]
> Actually it was pretty straightforward too, all you need is `CoRegisterClassObject`.

Thanks for the confirmation!
